services:
  - type: web
    name: drinks-system
    runtime: docker
    plan: free
    rootDir: .
    healthCheckPath: /order
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: supabase
      - key: SUPABASE_PROJECT_URL
        value: https://tmiwahcybsklinnymfpr.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_DB_URL
        value: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
      - key: SUPABASE_DB_USER
        value: postgres.tmiwahcybsklinnymfpr
      - key: SUPABASE_DB_PASSWORD
        sync: false
