create table branches (
  id bigint generated by default as identity primary key,
  name varchar(255),
  location varchar(255)
);

create table drinks (
  id bigint generated by default as identity primary key,
  name varchar(255),
  category varchar(255),
  price numeric(38,2)
);

create table orders (
  id bigint generated by default as identity primary key,
  customer_name varchar(255),
  customer_phone varchar(255),
  reference_number varchar(255),
  ordered_at timestamp(6),
  status varchar(255),
  total_amount numeric(38,2),
  amount_paid numeric(38,2),
  branch_id bigint,
  constraint fk_orders_branch foreign key (branch_id) references branches(id)
);

create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint,
  drink_id bigint,
  quantity integer,
  unit_price numeric(38,2),
  line_total numeric(38,2),
  constraint fk_order_items_order foreign key (order_id) references orders(id),
  constraint fk_order_items_drink foreign key (drink_id) references drinks(id)
);

create table stock_levels (
  id bigint generated by default as identity primary key,
  branch_id bigint,
  drink_id bigint,
  quantity integer,
  constraint fk_stock_levels_branch foreign key (branch_id) references branches(id),
  constraint fk_stock_levels_drink foreign key (drink_id) references drinks(id)
);
